services:
  db:
    image: mysql:8.0
    container_name: betalent_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betalent_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: payment_mocks
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  mysql_data:
